version: '3.7'
services:
  mongodb:
    image: mongo:4
    environment:
      MONGO_INITDB_DATABASE: 'mydb'
      # MONGO_INITDB_ROOT_USERNAME: 'root'
      # MONGO_INITDB_ROOT_PASSWORD: 'rootpassword'
    ports:
      - "27017:27017"
    volumes: 
      - ./db/:/data/db/
  mongo-express:
    image: mongo-express
    restart: always
    environment:
      # ME_CONFIG_MONGODB_ENABLE_ADMIN: 'true'
      # ME_CONFIG_MONGODB_ADMINUSERNAME: 'root'
      # ME_CONFIG_MONGODB_ADMINPASSWORD: 'rootpassword'
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_SERVER: 'mongodb'
    ports:
        - "8081:8081"
    depends_on:
        - mongodb